
version: 2

sources:
    - name: M360
      database: DB_M360_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: M360_DATA
    - name: SAP_HANA
      description: SAP Unify Database to get data from HANA
      database: DB_SAP_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: CUSTOMER
          description: Customer Master data (Key Customer)
        - name: CUSTOMER_CC
          description: Customer Company Code Master data (Key Customer, company code)
        - name: CONTACT
        - name: CONTACT_ROLE
        - name: COMPANY
        - name: LOCATION
          description: '{{ doc("Location_doc") }}'
          tests:
            - unique:
                column_name: "(source_system || site_code || update_time)"
        - name: MATERIAL
        - name: SALES_BILLING
        - name: VENDOR
        - name: COMPCODE
        - name: SALESCUBE_TEMP
        - name: PRMS_SALES