
version: 2

sources:
    - name: M360
      database: DB_M360_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: M360_DATA

    - name: SAP_HANA
      database: DB_SAP_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: CUSTOMER
        - name: CUSTOMER_CC
          columns:
                - name: company_code
                  tests:
                    - relationships:
                        to: ref('COMPCODE')
                        field: company_code
        - name: CONTACT
        - name: CONTACT_ROLE
        - name: COMPANY
        - name: LOCATION
          tests:
            - unique:
                column_name: "(source_system || site_code || update_time)"
          columns:
                - name: source_system
                  tests:
                    - accepted_values:
                       values: ['RHL ECC','LMK ECC']
        - name: MATERIAL
        - name: SALES_BILLING
        - name: VENDOR
        - name: PRMS_SALES