
version: 2

sources:
    - name: M360
      database: DB_M360_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: M360_DATA

    - name: SAP_HANA
      description: SAP Unify database
      database: DB_SAP_PROD
      schema: PUBLIC
      quoting:
        database: true
        schema: true
        identifier: true
      tables:
        - name: CUSTOMER
          description: Customer master 
        - name: CUSTOMER_CC
          description: Customer master cc view
          columns:
                - name: company_code
                  tests:
                    - relationships:
                        to: ref('COMPCODE')
                        field: company_code
        - name: CONTACT
          description: Contact master data
        - name: CONTACT_ROLE
          description: contact master data
        - name: COMPANY
          description: Company master data
        - name: LOCATION
          description: '{{ doc("Location_doc") }}'
          tests:
            - unique:
                column_name: "(source_system || site_code || update_time)"
          columns:
                - name: source_system
                  tests:
                    - accepted_values:
                       values: ['RHL ECC','LMK ECC']
        - name: MATERIAL
          description: Material master
        - name: SALES_BILLING
          freshness: 
            error_after:
              count: 10
              period: hour
          loaded_at_field: "convert_timezone('Australia/Sydney', 'UTC', update_time)"
          
          description: Sales and Billing transactional data
        - name: VENDOR
          description: vendor master
        - name: PRMS_SALES
          description: PRMS sales transactional data